const data ={
   products: [
       {
           _id:1,
           name:"NIKE Slim Shirts",
           category :"shirts",
           image : './images/p1.jpg',
           price: 120,
           countInStock:20,
           brand :'Nike',
           rating :4.5,
           numReviews : 10,
           description :'High Quality Products',
       },
       {
        _id:2,
        name:"NIKE Slim Shirts",
        category :"shirts",
        image : './images/p2.jpg',
        price: 120,countInStock:10,
        brand :'Nike',
        rating :2.5,
        numReviews : 10,
        description :'High Quality Products',
    },
    {
        _id:3,
        name:"Nike Slim Shirts",
        category :"shirts",
        image : './images/p3.jpg',
        price: 125,
        countInStock:30,
        brand :'Nike',
        rating :5,
        numReviews : 110,
        description :'High Quality Products',
    },
    {
        _id:4,
        name:"Nike Pants",
        category :"pants",
        image : './images/p5.jpg',
        price: 320,
        countInStock:24,
        brand :'Nike',
        rating :4.5,
        numReviews : 23,
        description :'High Quality Products',
    },
    {
        _id:5,
        name:"Nike Pants",
        category :"pants",
        image : './images/p4.jpg',
        price: 320,
        countInStock:33,
        brand :'Nike',
        rating :5,
        numReview : 123,
        description :'High Quality Products',
    },
    {
        _id:6,
        name:"Nike Pants",
        category :"pants",
        image : './images/p6.jpg',
        price: 320,
        countInStock:0,
        brand :'Nike',
        rating :4.5,
        numReviews : 23,
        description :'High Quality Products',
    },
    ]
}
// module.exports=data
export default data;